import { useState, useRef, useCallback } from 'react'
import { Zap, Cpu, Wifi, Server, MapPin, Clock, Download, CheckCircle2, RotateCcw, Hash } from 'lucide-react'

const C = {
  panel:  'rgba(255,255,255,0.03)',
  depth:  '#0d0d18',
  border: 'rgba(255,255,255,0.07)',
  text1:  'rgba(255,255,255,0.82)',
  text2:  'rgba(255,255,255,0.65)',
  text3:  'rgba(255,255,255,0.35)',
  accent: '#1a2eff',
  blue:   '#6b8cff',
  green:  '#22c55e',
  red:    '#ef4444',
  amber:  '#f59e0b',
  sans:   "'Outfit', sans-serif",
  mono:   "'JetBrains Mono', ui-monospace, monospace",
  rPanel: 16,
  rCard:  12,
  rBtn:   10,
}

const labelStyle = {
  display: 'flex', alignItems: 'center', gap: 5,
  fontSize: 11, fontWeight: 600,
  color: C.text3, marginBottom: 5, fontFamily: C.sans,
  textTransform: 'uppercase', letterSpacing: '0.06em',
}
const inputStyle = {
  width: '100%', padding: '8px 10px', fontSize: 12,
  background: 'rgba(255,255,255,0.04)',
  border: `1px solid ${C.border}`,
  borderRadius: 8, color: C.text1,
  fontFamily: C.sans, outline: 'none', boxSizing: 'border-box',
}

/* ── Firmware template generator ── */
function buildFirmwareScript({ ssid, password, broker, deviceId, location, ledPin, tzOffset }) {
  return `"""
IoT-Claw MicroPython Edge Agent — auto-generated by IoT-Claw Flash Wizard
Device: ${deviceId}  Location: ${location || 'unset'}
"""

import network, time, json, ntptime
from umqtt.simple import MQTTClient
from machine import Pin

WIFI_SSID   = "${ssid}"
WIFI_PASS   = "${password}"
MQTT_BROKER = "${broker}"
MQTT_PORT   = 1883
DEVICE_ID   = "${deviceId}"
TOPIC_BASE  = "home/esp32/" + DEVICE_ID
DISCOVERY_TOPIC = "home/discovery/" + DEVICE_ID
TZ_OFFSET_HOURS = ${tzOffset}

_status_led = Pin(${ledPin}, Pin.OUT)

CAPABILITIES = {
    "device_id": DEVICE_ID,
    "topic_base": TOPIC_BASE,
    "type": "micropython_edge_agent",
    "description": "MicroPython edge agent on ESP32 (" + DEVICE_ID + ")",
    "location": "${location}",
    "tools": [
        {"name":"set_led","description":"Control LED on GPIO ${ledPin}","params":{"state":["ON","OFF"]}},
        {"name":"read_adc","description":"Read ADC (0-4095) from a GPIO pin","params":{"pin":"int"}},
        {"name":"set_pin","description":"Set any GPIO pin high or low","params":{"pin":"int","state":["ON","OFF"]}},
        {"name":"exec_script","description":"Execute MicroPython via MQTT /script topic","params":{"code":"str"}}
    ]
}

_edge_globals = {}
_script_loaded = False

def connect_wifi():
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if wlan.isconnected(): return True
    wlan.connect(WIFI_SSID, WIFI_PASS)
    for _ in range(40):
        if wlan.isconnected():
            try: ntptime.settime()
            except: pass
            return True
        _status_led.value(not _status_led.value())
        time.sleep(0.25)
    return False

def edge_print(*args, **kwargs):
    msg = " ".join(str(a) for a in args)
    print("[EdgePrint]", msg)
    try: mqtt.publish(TOPIC_BASE + "/console", msg)
    except: pass

def on_message(topic, msg):
    global _edge_globals, _script_loaded
    topic = topic.decode(); msg = msg.decode().strip()
    if topic == TOPIC_BASE + "/script":
        _edge_globals = {"print": edge_print}
        try:
            with open("edge_logic.py", "w") as f:
                f.write(msg)
            exec(msg, _edge_globals)
            _script_loaded = "loop" in _edge_globals
            mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_loaded","ok":True}))
        except Exception as e:
            _script_loaded = False
            mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_error","error":str(e),"ok":False}))
    elif topic == TOPIC_BASE + "/set":
        if msg == "ON": _status_led.on()
        elif msg == "OFF": _status_led.off()
        mqtt.publish(TOPIC_BASE + "/state", msg)

if not connect_wifi():
    while True:
        _status_led.value(not _status_led.value()); time.sleep(0.1)

mqtt = MQTTClient(client_id=DEVICE_ID, server=MQTT_BROKER, port=MQTT_PORT, keepalive=30)
mqtt.set_callback(on_message)
mqtt.connect()
mqtt.publish(DISCOVERY_TOPIC, json.dumps(CAPABILITIES), retain=True)
mqtt.subscribe(TOPIC_BASE + "/set")
mqtt.subscribe(TOPIC_BASE + "/script")
_status_led.on(); time.sleep(0.2); _status_led.off()

_last_ping = _last_heartbeat = _last_telemetry = time.ticks_ms()
PING_MS = 25000; HB_MS = 30000; TEL_MS = 500

try:
    with open("edge_logic.py", "r") as f:
        script = f.read()
        _edge_globals = {"print": edge_print}
        exec(script, _edge_globals)
        _script_loaded = "loop" in _edge_globals
        mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_loaded_from_flash","ok":True}))
except Exception:
    pass

try:
    from machine import ADC
    _adc = ADC(Pin(34)); _adc.atten(ADC.ATTN_11DB); _has_adc = True
except: _has_adc = False

while True:
    try:
        mqtt.check_msg()
        now = time.ticks_ms()
        if _script_loaded and "loop" in _edge_globals:
            try: _edge_globals["loop"]()
            except: _script_loaded = False
        if time.ticks_diff(now, _last_heartbeat) > HB_MS:
            mqtt.publish(TOPIC_BASE + "/heartbeat", "alive"); _last_heartbeat = now
        if _has_adc and time.ticks_diff(now, _last_telemetry) > TEL_MS:
            mqtt.publish(TOPIC_BASE + "/state", str(_adc.read())); _last_telemetry = now
        if time.ticks_diff(now, _last_ping) > PING_MS:
            mqtt.ping(); _last_ping = now
        time.sleep_ms(100)
    except OSError:
        time.sleep(2)
        try:
            mqtt.connect()
            mqtt.subscribe(TOPIC_BASE + "/set"); mqtt.subscribe(TOPIC_BASE + "/script")
            mqtt.publish(DISCOVERY_TOPIC, json.dumps(CAPABILITIES), retain=True)
        except: time.sleep(5)
`
}

/* ── Steps ── */
const STEPS = ['Configure', 'Generate', 'Upload', 'Done']

const DEFAULT_CFG = {
  ssid: '', password: '', broker: '192.168.1.100',
  deviceId: 'esp32_edge_1', location: '', ledPin: '2', tzOffset: '0',
}

/* ── Serial upload helpers ── */
async function writeSerial(port, text) {
  const writer = port.writable.getWriter()
  const enc = new TextEncoder()
  await writer.write(enc.encode('\x01'))
  await new Promise(r => setTimeout(r, 300))
  await writer.write(enc.encode('\x04'))
  await new Promise(r => setTimeout(r, 800))
  await writer.write(enc.encode('\x01'))
  await new Promise(r => setTimeout(r, 300))
  const chunks = text.match(/.{1,256}/gs) || []
  for (const chunk of chunks) {
    await writer.write(enc.encode(chunk))
    await new Promise(r => setTimeout(r, 30))
  }
  await writer.write(enc.encode('\x04'))
  await new Promise(r => setTimeout(r, 500))
  writer.releaseLock()
}

/* ── Step progress bar ── */
function StepBar({ step }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', marginBottom: 28 }}>
      {STEPS.map((s, i) => (
        <div key={s} style={{ display: 'flex', alignItems: 'center', flex: i < STEPS.length - 1 ? 1 : 'none' }}>
          <div style={{
            width: 30, height: 30, flexShrink: 0,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 12, fontWeight: 700,
            fontFamily: C.mono,
            background: i < step ? C.green : i === step ? C.accent : 'rgba(255,255,255,0.04)',
            color: i <= step ? '#fff' : C.text3,
            border: i === step
              ? '1px solid rgba(26,46,255,0.6)'
              : i < step
                ? '1px solid rgba(34,197,94,0.4)'
                : `1px solid ${C.border}`,
            borderRadius: 8,
            transition: 'all 0.3s',
          }}>
            {i < step ? <CheckCircle2 size={14} /> : i + 1}
          </div>
          <div style={{ marginLeft: 8, flexShrink: 0 }}>
            <div style={{
              fontSize: 11, fontWeight: 700,
              letterSpacing: '0.07em', textTransform: 'uppercase',
              fontFamily: C.sans,
              color: i < step ? C.green : i === step ? C.accent : C.text3,
              transition: 'color 0.3s',
            }}>
              {s}
            </div>
          </div>
          {i < STEPS.length - 1 && (
            <div style={{
              flex: 1, height: 1, marginLeft: 8, marginRight: 8,
              background: i < step ? 'rgba(34,197,94,0.35)' : C.border,
              transition: 'background 0.3s',
            }} />
          )}
        </div>
      ))}
    </div>
  )
}

/* ── Form field helper ── */
function Field({ id, label, hint, required, children }) {
  return (
    <div>
      <label style={{ ...labelStyle, htmlFor: id }}>
        {label}
        {required && <span style={{ color: C.red, fontSize: 12 }}>*</span>}
      </label>
      {children}
      {hint && (
        <div style={{ fontSize: 10, color: C.text3, marginTop: 4, fontFamily: C.sans }}>{hint}</div>
      )}
    </div>
  )
}

/* ── Panel shell ── */
function Panel({ children, style }) {
  return (
    <div style={{
      background: C.panel,
      border: `1px solid ${C.border}`,
      borderRadius: C.rPanel,
      overflow: 'hidden',
      ...style,
    }}>
      {children}
    </div>
  )
}

function PanelHeader({ title, subtitle, badge }) {
  return (
    <div style={{
      padding: '14px 18px',
      borderBottom: `1px solid ${C.border}`,
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    }}>
      <div>
        <div style={{ fontSize: 14, fontWeight: 700, color: C.text1, fontFamily: C.sans }}>{title}</div>
        {subtitle && <div style={{ fontSize: 11, color: C.text3, marginTop: 2, fontFamily: C.sans }}>{subtitle}</div>}
      </div>
      {badge && (
        <span style={{
          fontSize: 9, padding: '3px 9px', borderRadius: 5,
          background: badge.green ? 'rgba(34,197,94,0.08)' : 'rgba(26,46,255,0.1)',
          border: badge.green ? '1px solid rgba(34,197,94,0.2)' : '1px solid rgba(26,46,255,0.2)',
          color: badge.green ? C.green : C.blue,
          fontFamily: C.mono, fontWeight: 700,
        }}>
          {badge.label}
        </span>
      )}
    </div>
  )
}

/* ── Component ── */
export default function FlashDevice() {
  const [step,     setStep]     = useState(0)
  const [cfg,      setCfg]      = useState(DEFAULT_CFG)
  const [script,   setScript]   = useState('')
  const [log,      setLog]      = useState([])
  const [flashing, setFlashing] = useState(false)
  const [done,     setDone]     = useState(false)
  const portRef = useRef(null)

  const update = (k, v) => setCfg(c => ({ ...c, [k]: v }))
  const addLog = useCallback(msg => setLog(l => [...l, msg]), [])

  const handleGenerate = () => {
    setScript(buildFirmwareScript(cfg))
    setStep(1)
  }

  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = 'main.py'; a.click()
    URL.revokeObjectURL(url)
    setStep(2)
  }

  const handleFlash = async () => {
    if (!('serial' in navigator)) {
      addLog('ERR  Web Serial API not supported. Use Chrome/Edge 89+.')
      return
    }
    setFlashing(true)
    setLog([])
    try {
      addLog('>>>  Requesting serial port…')
      const port = await navigator.serial.requestPort()
      portRef.current = port
      addLog('>>>  Opening port at 115200 baud…')
      await port.open({ baudRate: 115200 })
      addLog('OK   Port open. Entering MicroPython REPL…')
      await writeSerial(port, script)
      addLog('TX   Script sent to device!')
      addLog('...  Waiting for device to respond…')
      await new Promise(r => setTimeout(r, 1500))
      addLog('OK   Firmware pushed successfully!')
      addLog(`RDY  Device "${cfg.deviceId}" should appear in Dashboard shortly.`)
      await port.close()
      setDone(true)
      setStep(3)
    } catch (err) {
      addLog(`ERR  ${err.message}`)
    } finally {
      setFlashing(false)
    }
  }

  const reset = () => { setStep(0); setCfg(DEFAULT_CFG); setScript(''); setLog([]); setDone(false) }

  const canGenerate = cfg.ssid.trim() && cfg.broker.trim() && cfg.deviceId.trim()

  return (
    <div style={{ maxWidth: 760, margin: '0 auto' }}>

      {/* Page header */}
      <div style={{ marginBottom: 28, display: 'flex', alignItems: 'center', gap: 14 }}>
        <div style={{
          width: 50, height: 50, flexShrink: 0,
          background: 'rgba(26,46,255,0.12)',
          border: '1px solid rgba(26,46,255,0.28)',
          borderRadius: 14,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <Zap size={22} color={C.accent} />
        </div>
        <div>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 700, fontFamily: C.sans, color: C.text1 }}>
            Flash ESP32 Device
          </h1>
          <p style={{ margin: 0, fontSize: 12, color: C.text3, fontFamily: C.sans }}>
            One-click MicroPython firmware deployment
          </p>
        </div>
      </div>

      <StepBar step={step} />

      {/* ── Step 0: Configure ── */}
      {step === 0 && (
        <Panel>
          <PanelHeader title="Device Configuration" subtitle="WiFi, MQTT broker, and device identity" badge={{ label: 'Step 1 of 4' }} />
          <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 16 }}>

            {/* WiFi row */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <Field id="flash-ssid" label={<><Wifi size={12} style={{ verticalAlign: 'middle' }} /> WiFi SSID</>} required>
                <input id="flash-ssid" style={inputStyle} value={cfg.ssid} onChange={e => update('ssid', e.target.value)} placeholder="MyNetwork" />
              </Field>
              <Field id="flash-pass" label="WiFi Password">
                <input id="flash-pass" style={inputStyle} type="password" value={cfg.password} onChange={e => update('password', e.target.value)} placeholder="••••••••" />
              </Field>
            </div>

            {/* Broker */}
            <Field id="flash-broker" label={<><Server size={12} style={{ verticalAlign: 'middle' }} /> MQTT Broker IP</>} required hint="IP address of your Mosquitto broker">
              <input id="flash-broker" style={inputStyle} value={cfg.broker} onChange={e => update('broker', e.target.value)} placeholder="192.168.1.100" />
            </Field>

            {/* Device fields */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 110px 120px', gap: 14 }}>
              <Field id="flash-devid" label={<><Hash size={12} style={{ verticalAlign: 'middle' }} /> Device ID</>} required>
                <input id="flash-devid" style={inputStyle} value={cfg.deviceId} onChange={e => update('deviceId', e.target.value)} placeholder="esp32_edge_1" />
              </Field>
              <Field id="flash-loc" label={<><MapPin size={12} style={{ verticalAlign: 'middle' }} /> Location</>}>
                <input id="flash-loc" style={inputStyle} value={cfg.location} onChange={e => update('location', e.target.value)} placeholder="living_room" />
              </Field>
              <Field id="flash-tz" label={<><Clock size={12} style={{ verticalAlign: 'middle' }} /> TZ Offset</>}>
                <input id="flash-tz" type="number" style={inputStyle} value={cfg.tzOffset} onChange={e => update('tzOffset', e.target.value)} placeholder="-5" />
              </Field>
              <Field id="flash-pin" label={<><Cpu size={12} style={{ verticalAlign: 'middle' }} /> LED Pin</>}>
                <select id="flash-pin" style={inputStyle} value={cfg.ledPin} onChange={e => update('ledPin', e.target.value)}>
                  {['2','4','5','12','13','14','15','18','19','21','22','23','25','26','27'].map(p => (
                    <option key={p} value={p}>GPIO {p}{p === '2' ? ' ★' : ''}</option>
                  ))}
                </select>
              </Field>
            </div>

            {/* Info */}
            <div style={{
              padding: '10px 14px', borderRadius: 9, fontSize: 12, lineHeight: 1.7,
              background: 'rgba(107,140,255,0.07)', border: '1px solid rgba(107,140,255,0.15)', color: C.blue,
              fontFamily: C.sans,
            }}>
              Your ESP32 must already have <strong>MicroPython</strong> flashed on it.{' '}
              <a href="https://micropython.org/download/ESP32_GENERIC/" target="_blank" rel="noreferrer"
                style={{ color: C.blue, textDecoration: 'underline' }}>
                Download MicroPython firmware →
              </a>
            </div>

            <button
              id="flash-generate-btn"
              disabled={!canGenerate}
              onClick={handleGenerate}
              style={{
                padding: '13px 0', width: '100%',
                fontSize: 12, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase',
                border: 'none', cursor: canGenerate ? 'pointer' : 'not-allowed',
                background: canGenerate ? 'rgba(26,46,255,0.85)' : 'rgba(26,46,255,0.2)',
                color: canGenerate ? '#fff' : C.text3,
                borderRadius: C.rBtn, transition: 'all 0.2s', fontFamily: C.sans,
              }}
            >
              <Zap size={14} style={{ verticalAlign: 'middle', marginRight: 6 }} />
              Generate Firmware Script
            </button>
          </div>
        </Panel>
      )}

      {/* ── Step 1: Script preview ── */}
      {step === 1 && (
        <Panel>
          <PanelHeader title="Generated Firmware" subtitle="Review script before flashing to device" badge={{ label: 'Step 2 of 4' }} />
          <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{
              background: '#07090b',
              border: `1px solid ${C.border}`,
              borderRadius: 9,
              padding: '14px 16px',
              fontFamily: C.mono,
              fontSize: 11, color: C.green,
              lineHeight: 1.65,
              maxHeight: 320, overflowY: 'auto',
              whiteSpace: 'pre-wrap', wordBreak: 'break-all',
            }}>
              {script}
            </div>

            <div style={{ display: 'flex', gap: 12 }}>
              <button
                onClick={() => setStep(0)}
                style={{
                  flex: 1, padding: '11px 0', fontSize: 12, fontWeight: 600, cursor: 'pointer',
                  border: `1px solid ${C.border}`, background: 'rgba(255,255,255,0.03)',
                  color: C.text2, borderRadius: C.rBtn, fontFamily: C.sans,
                }}
              >
                ← Back
              </button>
              <button
                id="flash-download-btn"
                onClick={handleDownload}
                style={{
                  flex: 2, padding: '11px 0',
                  fontSize: 12, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase',
                  border: 'none', cursor: 'pointer',
                  background: 'rgba(26,46,255,0.85)', color: '#fff',
                  borderRadius: C.rBtn, fontFamily: C.sans,
                }}
              >
                <Download size={13} style={{ verticalAlign: 'middle', marginRight: 6 }} />
                Download main.py
              </button>
            </div>
          </div>
        </Panel>
      )}

      {/* ── Step 2: Upload ── */}
      {step === 2 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

          {/* Method A: Web Serial */}
          <Panel>
            <PanelHeader
              title="Method A — One-Click Web Serial Flash"
              subtitle="Requires Chrome / Edge 89+ with MicroPython already on device"
              badge={{ label: 'Recommended', green: true }}
            />
            <div style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div style={{
                padding: '10px 14px', borderRadius: 9, fontSize: 12,
                background: 'rgba(245,158,11,0.07)', border: '1px solid rgba(245,158,11,0.18)', color: C.amber,
                fontFamily: C.sans,
              }}>
                Plug your ESP32 via USB before clicking Flash. Hold the BOOT button while connecting if the port doesn't appear.
              </div>

              <button
                id="flash-serial-btn"
                onClick={handleFlash}
                disabled={flashing}
                style={{
                  padding: '13px 0', width: '100%',
                  fontSize: 12, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase',
                  border: 'none', cursor: flashing ? 'not-allowed' : 'pointer',
                  background: flashing ? 'rgba(26,46,255,0.25)' : 'rgba(26,46,255,0.85)',
                  color: '#fff',
                  borderRadius: C.rBtn, opacity: flashing ? 0.7 : 1, transition: 'all 0.2s',
                  fontFamily: C.sans,
                }}
              >
                <Zap size={13} style={{ verticalAlign: 'middle', marginRight: 6 }} />
                {flashing ? 'Flashing…' : 'Connect & Flash via Web Serial'}
              </button>

              {/* Serial log terminal */}
              {log.length > 0 && (
                <div style={{
                  background: '#07090b',
                  border: `1px solid ${C.border}`,
                  borderRadius: 9,
                  padding: '12px 14px',
                  fontFamily: C.mono,
                  fontSize: 11, lineHeight: 1.9,
                  maxHeight: 200, overflowY: 'auto',
                }}>
                  {log.map((l, i) => (
                    <div key={i} style={{
                      color: l.startsWith('ERR') ? C.red
                           : l.startsWith('OK') || l.startsWith('RDY') ? C.green
                           : l.startsWith('TX') ? C.blue
                           : '#94a3b8',
                    }}>
                      {l}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </Panel>

          {/* Method B: Manual */}
          <Panel>
            <PanelHeader title="Method B — Manual Upload (mpremote / Thonny)" subtitle="Use if Web Serial doesn't work on your system" badge={{ label: 'Manual' }} />
            <div style={{ padding: 20 }}>
              <ol style={{ margin: '0 0 12px 0', paddingLeft: 20, color: C.text2, fontSize: 12, lineHeight: 2, fontFamily: C.sans }}>
                <li>
                  Install{' '}
                  <code style={{ color: C.blue, background: 'rgba(26,46,255,0.1)', padding: '1px 6px', borderRadius: 4, fontFamily: C.mono }}>
                    mpremote
                  </code>
                  {': '}
                  <code style={{ color: '#94a3b8', fontFamily: C.mono }}>pip install mpremote</code>
                </li>
                <li>
                  Copy the downloaded{' '}
                  <code style={{ color: C.blue, background: 'rgba(26,46,255,0.1)', padding: '1px 6px', borderRadius: 4, fontFamily: C.mono }}>
                    main.py
                  </code>
                  {' '}to your ESP32:
                </li>
              </ol>

              <div style={{
                background: '#07090b',
                border: '1px solid rgba(34,197,94,0.12)',
                borderRadius: 8,
                padding: '10px 14px',
                fontFamily: C.mono,
                fontSize: 12, color: C.green,
              }}>
                mpremote connect auto cp main.py :main.py + reset
              </div>

              <div style={{ fontSize: 11, color: C.text3, marginTop: 10, fontFamily: C.sans }}>
                Or open <strong style={{ color: C.text2 }}>Thonny</strong>, connect to the ESP32,
                and save the file as{' '}
                <code style={{ color: C.blue, fontFamily: C.mono }}>main.py</code> on the device.
              </div>

              <button
                id="flash-done-manual-btn"
                onClick={() => setStep(3)}
                style={{
                  marginTop: 16, padding: '11px 0', width: '100%',
                  border: '1px solid rgba(34,197,94,0.3)',
                  background: 'rgba(34,197,94,0.07)',
                  color: C.green, cursor: 'pointer',
                  fontSize: 12, fontWeight: 700,
                  letterSpacing: '0.06em', textTransform: 'uppercase',
                  borderRadius: C.rBtn, transition: 'all 0.2s',
                  fontFamily: C.sans,
                }}
              >
                <CheckCircle2 size={13} style={{ verticalAlign: 'middle', marginRight: 6 }} />
                I've uploaded manually
              </button>
            </div>
          </Panel>
        </div>
      )}

      {/* ── Step 3: Done ── */}
      {step === 3 && (
        <Panel style={{ borderTop: `2px solid ${C.green}` }}>
          <div style={{
            padding: '52px 32px',
            display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 20,
            textAlign: 'center',
          }}>
            {/* Success icon */}
            <div style={{
              width: 76, height: 76,
              background: 'rgba(34,197,94,0.1)',
              border: '1px solid rgba(34,197,94,0.3)',
              borderRadius: 20,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              animation: 'fadeInUp 0.4s ease',
            }}>
              <CheckCircle2 size={36} color={C.green} />
            </div>

            <div>
              <div style={{ fontSize: 24, fontWeight: 700, color: C.text1, fontFamily: C.sans, marginBottom: 6 }}>
                Device Ready
              </div>
              <div style={{ fontSize: 13, color: C.text3, lineHeight: 1.7, fontFamily: C.sans }}>
                <span style={{ color: C.blue, fontFamily: C.mono }}>
                  {cfg.deviceId}
                </span>{' '}
                is now running the IoT-Claw edge agent.<br />
                It will auto-register in Devices once connected to your MQTT broker.
              </div>
            </div>

            {/* Summary table */}
            <div style={{
              background: 'rgba(255,255,255,0.02)',
              border: `1px solid ${C.border}`,
              borderRadius: 10,
              padding: '14px 20px',
              width: '100%', maxWidth: 420, textAlign: 'left',
            }}>
              {[
                ['Device ID', cfg.deviceId],
                ['Topic',     `home/esp32/${cfg.deviceId}`],
                ['Broker',    cfg.broker],
                ['Location',  cfg.location || '(not set)'],
              ].map(([k, v]) => (
                <div
                  key={k}
                  style={{
                    display: 'flex', justifyContent: 'space-between',
                    fontSize: 12, padding: '5px 0',
                    borderBottom: `1px solid ${C.border}`,
                    fontFamily: C.sans,
                  }}
                >
                  <span style={{ color: C.text3 }}>{k}</span>
                  <code style={{ color: C.blue, fontFamily: C.mono, fontSize: 11 }}>{v}</code>
                </div>
              ))}
            </div>

            <button
              id="flash-again-btn"
              onClick={reset}
              style={{
                padding: '11px 28px', fontSize: 12, fontWeight: 600, cursor: 'pointer',
                border: `1px solid ${C.border}`, background: 'rgba(255,255,255,0.04)',
                color: C.text2, borderRadius: C.rBtn, fontFamily: C.sans,
              }}
            >
              <RotateCcw size={13} style={{ verticalAlign: 'middle', marginRight: 6 }} />
              Flash Another Device
            </button>
          </div>
        </Panel>
      )}
    </div>
  )
}
