import { useState, useRef, useCallback } from 'react'

/* ── Firmware template generator ─────────────────────────────────────────── */
function buildFirmwareScript({ ssid, password, broker, deviceId, location, ledPin, tzOffset }) {
  return `"""
IoT-Claw MicroPython Edge Agent — auto-generated by IoT-Claw Flash Wizard
Device: ${deviceId}  Location: ${location || 'unset'}
"""

import network, time, json, ntptime
from umqtt.simple import MQTTClient
from machine import Pin

WIFI_SSID   = "${ssid}"
WIFI_PASS   = "${password}"
MQTT_BROKER = "${broker}"
MQTT_PORT   = 1883
DEVICE_ID   = "${deviceId}"
TOPIC_BASE  = "home/esp32/" + DEVICE_ID
DISCOVERY_TOPIC = "home/discovery/" + DEVICE_ID
TZ_OFFSET_HOURS = ${tzOffset}

_status_led = Pin(${ledPin}, Pin.OUT)

CAPABILITIES = {
    "device_id": DEVICE_ID,
    "topic_base": TOPIC_BASE,
    "type": "micropython_edge_agent",
    "description": "MicroPython edge agent on ESP32 (" + DEVICE_ID + ")",
    "location": "${location}",
    "tools": [
        {"name":"set_led","description":"Control LED on GPIO ${ledPin}","params":{"state":["ON","OFF"]}},
        {"name":"read_adc","description":"Read ADC (0-4095) from a GPIO pin","params":{"pin":"int"}},
        {"name":"set_pin","description":"Set any GPIO pin high or low","params":{"pin":"int","state":["ON","OFF"]}},
        {"name":"exec_script","description":"Execute MicroPython via MQTT /script topic","params":{"code":"str"}}
    ]
}

_edge_globals = {}
_script_loaded = False

def connect_wifi():
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if wlan.isconnected(): return True
    wlan.connect(WIFI_SSID, WIFI_PASS)
    for _ in range(40):
        if wlan.isconnected():
            try: ntptime.settime()
            except: pass
            return True
        _status_led.value(not _status_led.value())
        time.sleep(0.25)
    return False

def edge_print(*args, **kwargs):
    msg = " ".join(str(a) for a in args)
    print("[EdgePrint]", msg)
    try: mqtt.publish(TOPIC_BASE + "/console", msg)
    except: pass

def on_message(topic, msg):
    global _edge_globals, _script_loaded
    topic = topic.decode(); msg = msg.decode().strip()
    if topic == TOPIC_BASE + "/script":
        _edge_globals = {"print": edge_print}
        try:
            with open("edge_logic.py", "w") as f:
                f.write(msg)
            exec(msg, _edge_globals)
            _script_loaded = "loop" in _edge_globals
            mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_loaded","ok":True}))
        except Exception as e:
            _script_loaded = False
            mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_error","error":str(e),"ok":False}))
    elif topic == TOPIC_BASE + "/set":
        if msg == "ON": _status_led.on()
        elif msg == "OFF": _status_led.off()
        mqtt.publish(TOPIC_BASE + "/state", msg)

if not connect_wifi():
    while True:
        _status_led.value(not _status_led.value()); time.sleep(0.1)

mqtt = MQTTClient(client_id=DEVICE_ID, server=MQTT_BROKER, port=MQTT_PORT, keepalive=30)
mqtt.set_callback(on_message)
mqtt.connect()
mqtt.publish(DISCOVERY_TOPIC, json.dumps(CAPABILITIES), retain=True)
mqtt.subscribe(TOPIC_BASE + "/set")
mqtt.subscribe(TOPIC_BASE + "/script")
_status_led.on(); time.sleep(0.2); _status_led.off()

_last_ping = _last_heartbeat = _last_telemetry = time.ticks_ms()
PING_MS = 25000; HB_MS = 30000; TEL_MS = 500

try:
    with open("edge_logic.py", "r") as f:
        script = f.read()
        _edge_globals = {"print": edge_print}
        exec(script, _edge_globals)
        _script_loaded = "loop" in _edge_globals
        mqtt.publish(TOPIC_BASE + "/state", json.dumps({"status":"script_loaded_from_flash","ok":True}))
except Exception:
    pass

try:
    from machine import ADC
    _adc = ADC(Pin(34)); _adc.atten(ADC.ATTN_11DB); _has_adc = True
except: _has_adc = False

while True:
    try:
        mqtt.check_msg()
        now = time.ticks_ms()
        if _script_loaded and "loop" in _edge_globals:
            try: _edge_globals["loop"]()
            except: _script_loaded = False
        if time.ticks_diff(now, _last_heartbeat) > HB_MS:
            mqtt.publish(TOPIC_BASE + "/heartbeat", "alive"); _last_heartbeat = now
        if _has_adc and time.ticks_diff(now, _last_telemetry) > TEL_MS:
            mqtt.publish(TOPIC_BASE + "/state", str(_adc.read())); _last_telemetry = now
        if time.ticks_diff(now, _last_ping) > PING_MS:
            mqtt.ping(); _last_ping = now
        time.sleep_ms(100)
    except OSError:
        time.sleep(2)
        try:
            mqtt.connect()
            mqtt.subscribe(TOPIC_BASE + "/set"); mqtt.subscribe(TOPIC_BASE + "/script")
            mqtt.publish(DISCOVERY_TOPIC, json.dumps(CAPABILITIES), retain=True)
        except: time.sleep(5)
`
}

/* ── Steps ────────────────────────────────────────────────────────────────── */
const STEPS = ['Configure', 'Generate', 'Upload', 'Done']

const DEFAULT_CFG = {
  ssid: '', password: '', broker: '192.168.1.100',
  deviceId: 'esp32_edge_1', location: '', ledPin: '2', tzOffset: '0',
}

/* ── Serial upload helpers ────────────────────────────────────────────────── */
async function writeSerial(port, text) {
  const writer = port.writable.getWriter()
  const enc = new TextEncoder()
  // Enter raw REPL mode
  await writer.write(enc.encode('\x01')) // Ctrl-A
  await new Promise(r => setTimeout(r, 300))
  await writer.write(enc.encode('\x04')) // Ctrl-D soft reset
  await new Promise(r => setTimeout(r, 800))
  await writer.write(enc.encode('\x01')) // Ctrl-A raw repl
  await new Promise(r => setTimeout(r, 300))
  // Write script in chunks via ampy-style raw paste
  const chunks = text.match(/.{1,256}/gs) || []
  for (const chunk of chunks) {
    await writer.write(enc.encode(chunk))
    await new Promise(r => setTimeout(r, 30))
  }
  await writer.write(enc.encode('\x04')) // Ctrl-D execute
  await new Promise(r => setTimeout(r, 500))
  writer.releaseLock()
}

/* ─── Component ─────────────────────────────────────────────────────────── */
export default function FlashDevice() {
  const [step, setStep]       = useState(0)
  const [cfg, setCfg]         = useState(DEFAULT_CFG)
  const [script, setScript]   = useState('')
  const [log, setLog]         = useState([])
  const [flashing, setFlashing] = useState(false)
  const [done, setDone]       = useState(false)
  const portRef               = useRef(null)

  const update = (k, v) => setCfg(c => ({ ...c, [k]: v }))
  const addLog = useCallback(msg => setLog(l => [...l, msg]), [])

  /* Step 1 → 2 : generate script */
  const handleGenerate = () => {
    const s = buildFirmwareScript(cfg)
    setScript(s)
    setStep(1)
  }

  /* Step 2 → 3 : download + show upload instructions */
  const handleDownload = () => {
    const blob = new Blob([script], { type: 'text/plain' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url; a.download = 'main.py'; a.click()
    URL.revokeObjectURL(url)
    setStep(2)
  }

  /* Web Serial flash */
  const handleFlash = async () => {
    if (!('serial' in navigator)) {
      addLog('❌ Web Serial API not supported. Use Chrome/Edge 89+.')
      return
    }
    setFlashing(true)
    setLog([])
    try {
      addLog('🔌 Requesting serial port…')
      const port = await navigator.serial.requestPort()
      portRef.current = port
      addLog('📡 Opening port at 115200 baud…')
      await port.open({ baudRate: 115200 })
      addLog('✅ Port open. Entering MicroPython REPL…')
      await writeSerial(port, script)
      addLog('📤 Script sent to device!')
      addLog('⏳ Waiting for device to respond…')
      await new Promise(r => setTimeout(r, 1500))
      addLog('✅ Firmware pushed successfully!')
      addLog(`🚀 Device "${cfg.deviceId}" should appear in the dashboard shortly.`)
      await port.close()
      setDone(true)
      setStep(3)
    } catch (err) {
      addLog(`❌ Error: ${err.message}`)
    } finally {
      setFlashing(false)
    }
  }

  const reset = () => { setStep(0); setCfg(DEFAULT_CFG); setScript(''); setLog([]); setDone(false) }

  /* ── Render ─────────────────────────────────────────────────────────────── */
  return (
    <div style={{ maxWidth: 760, margin: '0 auto' }}>

      {/* Page header */}
      <div style={{ marginBottom: 28 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 6 }}>
          <div style={{
            width: 42, height: 42, borderRadius: 12,
            background: 'rgba(37,99,235,0.15)', border: '1px solid rgba(37,99,235,0.3)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20,
          }}>⚡</div>
          <div>
            <h1 style={{ margin: 0, fontSize: 22, fontWeight: 800, color: 'var(--text-main)' }}>Flash ESP32 Device</h1>
            <p style={{ margin: 0, fontSize: 12, color: 'var(--text-muted)' }}>One-click MicroPython firmware deployment</p>
          </div>
        </div>
      </div>

      {/* Step indicator */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 0, marginBottom: 28 }}>
        {STEPS.map((s, i) => (
          <div key={s} style={{ display: 'flex', alignItems: 'center', flex: i < STEPS.length - 1 ? 1 : 'none' }}>
            <div style={{
              width: 32, height: 32, borderRadius: '50%', flexShrink: 0,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 13, fontWeight: 700,
              background: i < step ? '#22c55e' : i === step ? 'var(--accent)' : 'var(--bg-dark)',
              color: i <= step ? '#fff' : 'var(--text-muted)',
              border: i === step ? '2px solid rgba(37,99,235,0.5)' : '1px solid rgba(255,255,255,0.06)',
              boxShadow: i === step ? '0 0 14px rgba(37,99,235,0.4)' : 'none',
              transition: 'all 0.3s',
            }}>
              {i < step ? '✓' : i + 1}
            </div>
            <div style={{ marginLeft: 8, marginRight: 8, flexShrink: 0 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: i <= step ? 'var(--text-main)' : 'var(--text-muted)' }}>{s}</div>
            </div>
            {i < STEPS.length - 1 && (
              <div style={{ flex: 1, height: 1, background: i < step ? 'rgba(34,197,94,0.4)' : 'rgba(255,255,255,0.06)', marginRight: 8 }} />
            )}
          </div>
        ))}
      </div>

      {/* ── Step 0: Configure ── */}
      {step === 0 && (
        <div className="neu-section">
          <div className="neu-section-header">
            <div>
              <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-main)' }}>Device Configuration</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Fill in your WiFi, MQTT and device settings</div>
            </div>
            <span className="neu-badge neu-badge-accent">Step 1</span>
          </div>
          <div className="neu-section-body" style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
              <div>
                <label className="neu-label" htmlFor="flash-ssid">WiFi SSID <span style={{ color: '#f87171' }}>*</span></label>
                <input id="flash-ssid" className="neu-input" value={cfg.ssid}
                  onChange={e => update('ssid', e.target.value)} placeholder="MyNetwork" />
              </div>
              <div>
                <label className="neu-label" htmlFor="flash-pass">WiFi Password</label>
                <input id="flash-pass" className="neu-input" type="password" value={cfg.password}
                  onChange={e => update('password', e.target.value)} placeholder="••••••••" />
              </div>
            </div>

            <div>
              <label className="neu-label" htmlFor="flash-broker">MQTT Broker IP <span style={{ color: '#f87171' }}>*</span></label>
              <input id="flash-broker" className="neu-input" value={cfg.broker}
                onChange={e => update('broker', e.target.value)} placeholder="192.168.1.100" />
              <div style={{ fontSize: 10, color: 'var(--text-muted)', marginTop: 4 }}>IP address of your Mosquitto broker</div>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 100px 100px', gap: 14 }}>
              <div>
                <label className="neu-label" htmlFor="flash-devid">Device ID <span style={{ color: '#f87171' }}>*</span></label>
                <input id="flash-devid" className="neu-input" value={cfg.deviceId}
                  onChange={e => update('deviceId', e.target.value)} placeholder="esp32_edge_1" />
              </div>
              <div>
                <label className="neu-label" htmlFor="flash-loc">Location</label>
                <input id="flash-loc" className="neu-input" value={cfg.location}
                  onChange={e => update('location', e.target.value)} placeholder="living_room" />
              </div>
              <div>
                <label className="neu-label" htmlFor="flash-tz">TZ Offset</label>
                <input id="flash-tz" type="number" className="neu-input" value={cfg.tzOffset}
                  onChange={e => update('tzOffset', e.target.value)} placeholder="e.g. -5" />
              </div>
              <div>
                <label className="neu-label" htmlFor="flash-pin">LED Pin</label>
                <select id="flash-pin" className="neu-input" value={cfg.ledPin} onChange={e => update('ledPin', e.target.value)}>
                  {['2','4','5','12','13','14','15','18','19','21','22','23','25','26','27'].map(p => (
                    <option key={p} value={p}>GPIO {p}{p === '2' ? ' (built-in)' : ''}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Info box */}
            <div className="neu-alert-info" style={{ fontSize: 12, lineHeight: 1.7 }}>
              ℹ️ Your ESP32 must already have <strong>MicroPython</strong> flashed on it.
              {' '}<a href="https://micropython.org/download/ESP32_GENERIC/" target="_blank" rel="noreferrer"
                style={{ color: 'var(--accent-light)', textDecoration: 'underline' }}>
                Download MicroPython firmware →
              </a>
            </div>

            <button id="flash-generate-btn"
              disabled={!cfg.ssid.trim() || !cfg.broker.trim() || !cfg.deviceId.trim()}
              onClick={handleGenerate}
              style={{
                padding: '13px 0', width: '100%', fontSize: 13, fontWeight: 700,
                letterSpacing: '0.05em', textTransform: 'uppercase', border: 'none',
                borderRadius: 10, cursor: 'pointer',
                background: 'var(--accent)', color: '#fff',
                boxShadow: '0 4px 14px rgba(37,99,235,0.35)',
                opacity: (!cfg.ssid.trim() || !cfg.broker.trim() || !cfg.deviceId.trim()) ? 0.4 : 1,
                transition: 'opacity 0.2s',
              }}>
              ⚡ Generate Firmware Script →
            </button>
          </div>
        </div>
      )}

      {/* ── Step 1: Generated script preview ── */}
      {step === 1 && (
        <div className="neu-section">
          <div className="neu-section-header">
            <div>
              <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-main)' }}>Generated Firmware</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Review the script before uploading to your device</div>
            </div>
            <span className="neu-badge neu-badge-accent">Step 2</span>
          </div>
          <div className="neu-section-body" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            <div style={{
              background: '#0d0f11', borderRadius: 10, padding: '14px 16px',
              fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: '#22c55e',
              lineHeight: 1.6, maxHeight: 320, overflowY: 'auto',
              border: '1px solid rgba(34,197,94,0.12)',
              whiteSpace: 'pre-wrap', wordBreak: 'break-all',
            }}>
              {script}
            </div>
            <div style={{ display: 'flex', gap: 12 }}>
              <button onClick={() => setStep(0)}
                style={{ flex: 1, padding: '11px 0', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 10, background: 'var(--bg-card2)', color: 'var(--text-dim)', cursor: 'pointer', fontWeight: 600 }}>
                ← Back
              </button>
              <button id="flash-download-btn" onClick={handleDownload}
                style={{ flex: 2, padding: '11px 0', border: 'none', borderRadius: 10, background: 'var(--accent)', color: '#fff', cursor: 'pointer', fontWeight: 700, fontSize: 13, boxShadow: '0 4px 14px rgba(37,99,235,0.35)' }}>
                ⬇ Download main.py →
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Step 2: Upload ── */}
      {step === 2 && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          {/* Method A: Web Serial */}
          <div className="neu-section">
            <div className="neu-section-header">
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-main)' }}>Method A — One-Click Web Serial Flash</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Requires Chrome / Edge 89+ and MicroPython already on device</div>
              </div>
              <span className="neu-badge neu-badge-green">Recommended</span>
            </div>
            <div className="neu-section-body" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              <div className="neu-alert-warn" style={{ fontSize: 12 }}>
                ⚠️ Plug your ESP32 via USB before clicking Flash. Hold the BOOT button while connecting if the port doesn't appear.
              </div>
              <button id="flash-serial-btn" onClick={handleFlash} disabled={flashing}
                style={{
                  padding: '13px 0', width: '100%', fontSize: 13, fontWeight: 700,
                  letterSpacing: '0.05em', textTransform: 'uppercase', border: 'none',
                  borderRadius: 10, cursor: flashing ? 'not-allowed' : 'pointer',
                  background: flashing ? '#1a2540' : 'var(--accent)', color: '#fff',
                  boxShadow: flashing ? 'none' : '0 4px 14px rgba(37,99,235,0.35)',
                  opacity: flashing ? 0.7 : 1, transition: 'all 0.2s',
                }}>
                {flashing ? '⚡ Flashing…' : '⚡ Connect & Flash via Web Serial'}
              </button>

              {/* Serial log */}
              {log.length > 0 && (
                <div style={{
                  background: '#0d0f11', borderRadius: 10, padding: '12px 14px',
                  fontFamily: "'JetBrains Mono', monospace", fontSize: 11,
                  lineHeight: 1.8, border: '1px solid rgba(255,255,255,0.05)',
                  maxHeight: 200, overflowY: 'auto',
                }}>
                  {log.map((l, i) => (
                    <div key={i} style={{ color: l.startsWith('❌') ? '#f87171' : l.startsWith('✅') || l.startsWith('🚀') ? '#22c55e' : '#94a3b8' }}>
                      {l}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Method B: Manual */}
          <div className="neu-section">
            <div className="neu-section-header">
              <div>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-main)' }}>Method B — Manual Upload (mpremote / Thonny)</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Use if Web Serial doesn't work on your system</div>
              </div>
              <span className="neu-badge">Manual</span>
            </div>
            <div className="neu-section-body">
              <ol style={{ margin: 0, paddingLeft: 20, color: 'var(--text-dim)', fontSize: 13, lineHeight: 2 }}>
                <li>Install <code style={{ color: 'var(--accent-light)', background: 'rgba(37,99,235,0.1)', padding: '1px 6px', borderRadius: 4 }}>mpremote</code>: <code style={{ color: '#94a3b8' }}>pip install mpremote</code></li>
                <li>Copy the downloaded <code style={{ color: 'var(--accent-light)', background: 'rgba(37,99,235,0.1)', padding: '1px 6px', borderRadius: 4 }}>main.py</code> to your ESP32:</li>
              </ol>
              <div style={{
                background: '#0d0f11', borderRadius: 8, padding: '10px 14px', marginTop: 10,
                fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: '#22c55e',
                border: '1px solid rgba(34,197,94,0.1)',
              }}>
                mpremote connect auto cp main.py :main.py + reset
              </div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 10 }}>
                Or open <strong style={{ color: 'var(--text-dim)' }}>Thonny</strong>, connect to the ESP32, and save the file as <code style={{ color: 'var(--accent-light)' }}>main.py</code> on the device.
              </div>
              <button id="flash-done-manual-btn" onClick={() => setStep(3)}
                style={{
                  marginTop: 16, padding: '11px 0', width: '100%',
                  border: '1px solid rgba(34,197,94,0.3)', borderRadius: 10,
                  background: 'rgba(34,197,94,0.08)', color: '#22c55e',
                  cursor: 'pointer', fontWeight: 700, fontSize: 13,
                }}>
                ✓ I've uploaded manually →
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Step 3: Done ── */}
      {step === 3 && (
        <div className="neu-section" style={{ textAlign: 'center' }}>
          <div className="neu-section-body" style={{ padding: '48px 32px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
            <div style={{
              width: 72, height: 72, borderRadius: '50%',
              background: 'rgba(34,197,94,0.12)', border: '2px solid rgba(34,197,94,0.3)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 36, boxShadow: '0 0 24px rgba(34,197,94,0.2)',
              animation: 'fadeInScale 0.4s ease',
            }}>🚀</div>
            <div>
              <div style={{ fontSize: 22, fontWeight: 800, color: 'var(--text-main)', marginBottom: 6 }}>Device Ready!</div>
              <div style={{ fontSize: 13, color: 'var(--text-muted)', lineHeight: 1.7 }}>
                <strong style={{ color: 'var(--accent-light)' }}>{cfg.deviceId}</strong> is now running the IoT-Claw edge agent.<br />
                It will auto-register in the Devices tab once it connects to your MQTT broker.
              </div>
            </div>

            <div style={{
              background: 'var(--bg-dark)', borderRadius: 12, padding: '14px 20px',
              display: 'flex', flexDirection: 'column', gap: 8, width: '100%', maxWidth: 400,
              border: '1px solid rgba(255,255,255,0.05)', textAlign: 'left',
            }}>
              {[
                ['Device ID', cfg.deviceId],
                ['Topic', `home/esp32/${cfg.deviceId}`],
                ['Broker', cfg.broker],
                ['Location', cfg.location || '(not set)'],
              ].map(([k, v]) => (
                <div key={k} style={{ display: 'flex', justifyContent: 'space-between', fontSize: 12 }}>
                  <span style={{ color: 'var(--text-muted)' }}>{k}</span>
                  <code style={{ color: 'var(--accent-light)', fontFamily: "'JetBrains Mono', monospace" }}>{v}</code>
                </div>
              ))}
            </div>

            <div style={{ display: 'flex', gap: 12, width: '100%', maxWidth: 400 }}>
              <button id="flash-again-btn" onClick={reset}
                style={{ flex: 1, padding: '11px 0', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 10, background: 'var(--bg-card2)', color: 'var(--text-dim)', cursor: 'pointer', fontWeight: 600 }}>
                ⚡ Flash Another
              </button>
            </div>
          </div>
        </div>
      )}

      <style>{`
        @keyframes fadeInScale {
          from { opacity: 0; transform: scale(0.7); }
          to   { opacity: 1; transform: scale(1); }
        }
      `}</style>
    </div>
  )
}
